plugins { id 'com.android.application' }
android {
    namespace 'io.onloopio'
    compileSdk 35
    defaultConfig {
        applicationId 'io.onloopio'
        minSdk 17
        targetSdk 17
        versionCode 15
        versionName '0.9.0'
        testInstrumentationRunner 'io.onloopio.OnLoopioTestRunner'
        ndk { abiFilters 'armeabi-v7a' }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildTypes {
        debug { debuggable true }
        release { debuggable false; minifyEnabled false }
    }
    if (rootProject.file('.local/debug.keystore').exists()) {
        signingConfigs.debug.storeFile rootProject.file('.local/debug.keystore')
    }
    lint { disable 'ExpiredTargetSdkVersion', 'OldTargetApi' }
}
dependencies { implementation 'org.conscrypt:conscrypt-android:2.5.2' }
